package com.daimler.mbcarkit.persistance.model

import io.realm.RealmObject
import io.realm.annotations.PrimaryKey

internal open class RealmVehicleState : RealmObject() {

    @PrimaryKey
    var finOrVin: String = ""

    var auxheatActiveState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var auxHeatRuntime: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var auxheatState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var auxheatTime1: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var auxheatTime2: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var auxheatTime3: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var auxheatTimeSelection: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var auxheatWarnings: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var averageSpeedReset: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var averageSpeedStart: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var batteryState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargingActive: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargingError: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargingMode: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargingStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var clientMessageData: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble() // Data in model from christoph --> not defined
    var decklidState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var decklidLockState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var distanceElectricalReset: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var distanceElectricalStart: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var distanceGasReset: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var distanceGasStart: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var distanceReset: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var distanceStart: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var distanceZeReset: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var distanceZeStart: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var doorLockStateFrontLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var doorStateFrontLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var doorLockStateFrontRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var doorStateFrontRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var doorLockStateGas: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var doorLockStateRearLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var doorStateRearLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var doorLockStateRearRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var doorStateRearRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var drivenTimeReset: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var drivenTimeStart: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var drivenTimeZEReset: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var drivenTimeZEStart: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var ecoScoreAccel: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var ecoScoreBonusRange: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var ecoScoreConst: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var ecoScoreFreeWhl: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var ecoScoreTotal: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var electricConsumptionReset: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var electricConsumptionStart: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var electricalRangeSkipIndication: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var engineState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var engineHoodStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var eventTimeStamp: Long = 0
    var filterParticelState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var gasConsumptionReset: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var gasConsumptionStart: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var healthStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var hybridWarnings: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var ignitionState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var interiorProtectionStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var keyActivationState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var languageHu: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var lastParkEvent: RealmVehicleAttributeLong? = RealmVehicleAttributeLong()
    var lastParkEventNotConfirmed: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var parkEventSensorStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var liquidConsumptionReset: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var liquidConsumptionStart: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var liquidRangeSkipIndication: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var lockStatusOverall: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var maxSoc: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var maxSocLowerLimit: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var odo: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var overallRange: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var parkBrakeState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var parkEventLevel: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var parkEventType: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var positionHeading: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var positionLat: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var positionLong: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var positionErrorCode: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var proximityRequiredForLocation: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var remoteStartActive: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var remoteStartTemperature: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var remoteStartEndtime: RealmVehicleAttributeLong? = RealmVehicleAttributeLong()
    var rooftopState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var selectedChargeProgram: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var serviceIntervalDays: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var serviceIntervalDistance: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var smartCharging: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var smartChargingDeparture: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var smartChargingDeparture2: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var sequenceNumber: Int? = null
    var soc: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var speedAlertConfiguration: RealmVehicleAttributeSpeedAlertConfiguration? = RealmVehicleAttributeSpeedAlertConfiguration()
    var speedUnitFromIc: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var stateOverall: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var sunroofEventState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var sunroofEventActive: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var sunroofState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var sunroofStatusFrontBlind: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var sunroofStatusRearBlind: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var teenageDrivingMode: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tankAdBlueLevel: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tankElectricalLevel: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tankElectricalRange: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tankGasLevel: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var tankGasRange: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var tankLiquidLevel: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tankLiquidRange: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var temperaturePointFrontCenter: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var temperaturePointFrontLeft: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var temperaturePointFrontRight: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var temperaturePointRearCenter: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var temperaturePointRearCenter2: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var temperaturePointRearLeft: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var temperaturePointRearRight: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var temperatureUnitHu: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var theftAlarmActive: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var theftSystemArmed: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var timeFormatHu: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tireLevelPrw: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tirePressureFrontLeft: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var tirePressureFrontRight: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var tirePressureRearLeft: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var tirePressureRearRight: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var tireMarkerFrontLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tireMarkerFrontRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tireMarkerRearLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tireMarkerRearRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var tirePressureMeasurementTimestamp: RealmVehicleAttributeLong? = RealmVehicleAttributeLong()
    var tireSensorAvailable: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var towProtectionSensorStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var trackingStateHu: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var valetDrivingMode: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var vehicleDataConnectionState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var vehicleLockState: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var vTime: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var warningBrakeFluid: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var warningBrakeLiningWear: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var warningCoolantLevelLow: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var warningEngineLight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var warningLowBattery: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var warningTireLamp: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var warningTireSprw: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var warningTireSrdk: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var warningWashWater: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var weekdayTariff: RealmVehicleAttributeTariff? = RealmVehicleAttributeTariff()
    var weekendTariff: RealmVehicleAttributeTariff? = RealmVehicleAttributeTariff()
    var windowStatusRearBlind: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var windowStatusRearLeftBlind: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var windowStatusRearRightBlind: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var windowStateFrontLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var windowStateFrontRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var windowStateRearLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var windowStateRearRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var windowStateOverall: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var flipWindowStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var weeklySetHU: RealmVehicleAttributeWeeklySetHU? = RealmVehicleAttributeWeeklySetHU()
    var weeklyProfile: RealmVehicleAttributeWeeklyProfile? = RealmVehicleAttributeWeeklyProfile()
    var zevActive: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()

    var chargingPower: RealmVehicleAttributeDouble? = RealmVehicleAttributeDouble()
    var departureTime: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var departureTimeMode: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var departureTimeSoc: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var departureTimeWeekday: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var endOfChargeTime: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var endOfChargeTimeRelative: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var endOfChargeTimeWeekday: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var maxRange: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondActive: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondAtDeparture: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondAtDepartureDisable: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondDuration: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondError: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondNow: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondNowError: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondSeatFrontRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondSeatFrontLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondSeatRearRight: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var precondSeatRearLeft: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var socprofile: RealmVehicleAttributeSocProfile? = RealmVehicleAttributeSocProfile()
    var chargingProgram: RealmVehicleAttributeChargingProgram? = RealmVehicleAttributeChargingProgram()
    var bidirectionalChargingActive: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var minSoc: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var acChargingCurrentLimitation: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargingErrorInfrastructure: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargingTimeType: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var minSocLowerLimit: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var nextDepartureTime: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var nextDepartureTimeWeekday: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var departureTimeIcon: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargingErrorWim: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var maxSocUpperLimit: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var minSocUpperLimit: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargingPowerEcoLimit: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargeFlapDCStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargeFlapACStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargeCouplerDCLockStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargeCouplerACLockStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargeCouplerDCStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargeCouplerACStatus: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var evRangeAssistDriveOnTime: RealmVehicleAttributeLong? = RealmVehicleAttributeLong()
    var evRangeAssistDriveOnSOC: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var chargingBreakClockTimer: RealmVehicleAttributeChargingBreakClockTimer? = RealmVehicleAttributeChargingBreakClockTimer()
    var chargingPowerControl: RealmVehicleAttributeChargingPowerControl? = RealmVehicleAttributeChargingPowerControl()

    var lastTheftWarningReason: RealmVehicleAttributeInt? = RealmVehicleAttributeInt()
    var lastTheftWarning: RealmVehicleAttributeLong? = RealmVehicleAttributeLong()

    internal fun cascadeDeleteFromRealm() {
        auxheatActiveState?.deleteFromRealm()
        auxHeatRuntime?.deleteFromRealm()
        auxheatState?.deleteFromRealm()
        auxheatTime1?.deleteFromRealm()
        auxheatTime2?.deleteFromRealm()
        auxheatTime3?.deleteFromRealm()
        auxheatTimeSelection?.deleteFromRealm()
        auxheatWarnings?.deleteFromRealm()
        averageSpeedReset?.deleteFromRealm()
        averageSpeedStart?.deleteFromRealm()
        batteryState?.deleteFromRealm()
        chargingActive?.deleteFromRealm()
        chargingError?.deleteFromRealm()
        chargingMode?.deleteFromRealm()
        chargingPower?.deleteFromRealm()
        chargingStatus?.deleteFromRealm()
        clientMessageData?.deleteFromRealm()
        decklidLockState?.deleteFromRealm()
        decklidState?.deleteFromRealm()
        departureTime?.deleteFromRealm()
        departureTimeMode?.deleteFromRealm()
        departureTimeSoc?.deleteFromRealm()
        departureTimeWeekday?.deleteFromRealm()
        distanceElectricalReset?.deleteFromRealm()
        distanceElectricalStart?.deleteFromRealm()
        distanceGasReset?.deleteFromRealm()
        distanceGasStart?.deleteFromRealm()
        distanceReset?.deleteFromRealm()
        distanceStart?.deleteFromRealm()
        distanceZeReset?.deleteFromRealm()
        distanceZeStart?.deleteFromRealm()
        doorLockStateFrontLeft?.deleteFromRealm()
        doorLockStateFrontRight?.deleteFromRealm()
        doorLockStateGas?.deleteFromRealm()
        doorLockStateRearLeft?.deleteFromRealm()
        doorLockStateRearRight?.deleteFromRealm()
        doorStateFrontLeft?.deleteFromRealm()
        doorStateFrontRight?.deleteFromRealm()
        doorStateRearLeft?.deleteFromRealm()
        doorStateRearRight?.deleteFromRealm()
        drivenTimeReset?.deleteFromRealm()
        drivenTimeStart?.deleteFromRealm()
        drivenTimeZEReset?.deleteFromRealm()
        drivenTimeZEStart?.deleteFromRealm()
        ecoScoreAccel?.deleteFromRealm()
        ecoScoreBonusRange?.deleteFromRealm()
        ecoScoreConst?.deleteFromRealm()
        ecoScoreFreeWhl?.deleteFromRealm()
        ecoScoreTotal?.deleteFromRealm()
        electricalRangeSkipIndication?.deleteFromRealm()
        electricConsumptionReset?.deleteFromRealm()
        electricConsumptionStart?.deleteFromRealm()
        endOfChargeTime?.deleteFromRealm()
        endOfChargeTimeRelative?.deleteFromRealm()
        endOfChargeTimeWeekday?.deleteFromRealm()
        engineHoodStatus?.deleteFromRealm()
        engineState?.deleteFromRealm()
        filterParticelState?.deleteFromRealm()
        flipWindowStatus?.deleteFromRealm()
        gasConsumptionReset?.deleteFromRealm()
        gasConsumptionStart?.deleteFromRealm()
        healthStatus?.deleteFromRealm()
        hybridWarnings?.deleteFromRealm()
        ignitionState?.deleteFromRealm()
        interiorProtectionStatus?.deleteFromRealm()
        keyActivationState?.deleteFromRealm()
        languageHu?.deleteFromRealm()
        lastParkEvent?.deleteFromRealm()
        lastParkEventNotConfirmed?.deleteFromRealm()
        lastTheftWarning?.deleteFromRealm()
        lastTheftWarningReason?.deleteFromRealm()
        liquidConsumptionReset?.deleteFromRealm()
        liquidConsumptionStart?.deleteFromRealm()
        liquidRangeSkipIndication?.deleteFromRealm()
        lockStatusOverall?.deleteFromRealm()
        maxRange?.deleteFromRealm()
        maxSoc?.deleteFromRealm()
        maxSocLowerLimit?.deleteFromRealm()
        odo?.deleteFromRealm()
        overallRange?.deleteFromRealm()
        parkBrakeState?.deleteFromRealm()
        parkEventLevel?.deleteFromRealm()
        parkEventSensorStatus?.deleteFromRealm()
        parkEventType?.deleteFromRealm()
        positionHeading?.deleteFromRealm()
        positionLat?.deleteFromRealm()
        positionLong?.deleteFromRealm()
        positionErrorCode?.deleteFromRealm()
        proximityRequiredForLocation?.deleteFromRealm()
        precondActive?.deleteFromRealm()
        precondAtDeparture?.deleteFromRealm()
        precondAtDepartureDisable?.deleteFromRealm()
        precondDuration?.deleteFromRealm()
        precondError?.deleteFromRealm()
        precondNow?.deleteFromRealm()
        precondNowError?.deleteFromRealm()
        precondSeatFrontLeft?.deleteFromRealm()
        precondSeatFrontRight?.deleteFromRealm()
        precondSeatRearLeft?.deleteFromRealm()
        precondSeatRearRight?.deleteFromRealm()
        remoteStartActive?.deleteFromRealm()
        remoteStartEndtime?.deleteFromRealm()
        remoteStartTemperature?.deleteFromRealm()
        rooftopState?.deleteFromRealm()
        selectedChargeProgram?.deleteFromRealm()
        serviceIntervalDays?.deleteFromRealm()
        serviceIntervalDistance?.deleteFromRealm()
        smartCharging?.deleteFromRealm()
        smartChargingDeparture2?.deleteFromRealm()
        smartChargingDeparture?.deleteFromRealm()
        soc?.deleteFromRealm()
        socprofile?.soc?.deleteAllFromRealm()
        socprofile?.times?.deleteAllFromRealm()
        socprofile?.deleteFromRealm()
        chargingProgram?.chargingPrograms?.deleteAllFromRealm()
        chargingProgram?.deleteFromRealm()
        speedAlertConfiguration?.deleteFromRealm()
        speedUnitFromIc?.deleteFromRealm()
        stateOverall?.deleteFromRealm()
        sunroofEventActive?.deleteFromRealm()
        sunroofEventState?.deleteFromRealm()
        sunroofState?.deleteFromRealm()
        sunroofStatusFrontBlind?.deleteFromRealm()
        sunroofStatusRearBlind?.deleteFromRealm()
        tankAdBlueLevel?.deleteFromRealm()
        tankElectricalLevel?.deleteFromRealm()
        tankElectricalRange?.deleteFromRealm()
        tankGasLevel?.deleteFromRealm()
        tankGasRange?.deleteFromRealm()
        tankLiquidLevel?.deleteFromRealm()
        tankLiquidRange?.deleteFromRealm()
        teenageDrivingMode?.deleteFromRealm()
        temperaturePointFrontCenter?.deleteFromRealm()
        temperaturePointFrontLeft?.deleteFromRealm()
        temperaturePointFrontRight?.deleteFromRealm()
        temperaturePointRearCenter2?.deleteFromRealm()
        temperaturePointRearCenter?.deleteFromRealm()
        temperaturePointRearLeft?.deleteFromRealm()
        temperaturePointRearRight?.deleteFromRealm()
        temperatureUnitHu?.deleteFromRealm()
        theftAlarmActive?.deleteFromRealm()
        theftSystemArmed?.deleteFromRealm()
        timeFormatHu?.deleteFromRealm()
        tireLevelPrw?.deleteFromRealm()
        tirePressureFrontLeft?.deleteFromRealm()
        tirePressureFrontRight?.deleteFromRealm()
        tirePressureMeasurementTimestamp?.deleteFromRealm()
        tirePressureRearLeft?.deleteFromRealm()
        tirePressureRearRight?.deleteFromRealm()
        tireSensorAvailable?.deleteFromRealm()
        towProtectionSensorStatus?.deleteFromRealm()
        trackingStateHu?.deleteFromRealm()
        valetDrivingMode?.deleteFromRealm()
        vehicleDataConnectionState?.deleteFromRealm()
        vehicleLockState?.deleteFromRealm()
        vTime?.deleteFromRealm()
        warningBrakeFluid?.deleteFromRealm()
        warningBrakeLiningWear?.deleteFromRealm()
        warningCoolantLevelLow?.deleteFromRealm()
        warningEngineLight?.deleteFromRealm()
        warningLowBattery?.deleteFromRealm()
        warningTireLamp?.deleteFromRealm()
        warningTireSprw?.deleteFromRealm()
        warningTireSrdk?.deleteFromRealm()
        warningWashWater?.deleteFromRealm()
        weekdayTariff?.rates?.deleteAllFromRealm()
        weekdayTariff?.times?.deleteAllFromRealm()
        weekdayTariff?.deleteFromRealm()
        weekendTariff?.rates?.deleteAllFromRealm()
        weekendTariff?.times?.deleteAllFromRealm()
        weekendTariff?.deleteFromRealm()
        weeklyProfile?.timeProfiles?.toList()?.forEach { it.days?.deleteAllFromRealm() }
        weeklyProfile?.timeProfiles?.deleteAllFromRealm()
        weeklyProfile?.deleteFromRealm()
        weeklySetHU?.day?.deleteAllFromRealm()
        weeklySetHU?.time?.deleteAllFromRealm()
        weeklySetHU?.deleteFromRealm()
        windowStatusRearBlind?.deleteFromRealm()
        windowStatusRearLeftBlind?.deleteFromRealm()
        windowStatusRearRightBlind?.deleteFromRealm()
        windowStateFrontLeft?.deleteFromRealm()
        windowStateFrontRight?.deleteFromRealm()
        windowStateOverall?.deleteFromRealm()
        windowStateRearLeft?.deleteFromRealm()
        windowStateRearRight?.deleteFromRealm()
        zevActive?.deleteFromRealm()
        bidirectionalChargingActive?.deleteFromRealm()
        minSoc?.deleteFromRealm()
        acChargingCurrentLimitation?.deleteFromRealm()
        chargingErrorInfrastructure?.deleteFromRealm()
        chargingTimeType?.deleteFromRealm()
        minSocLowerLimit?.deleteFromRealm()
        nextDepartureTime?.deleteFromRealm()
        nextDepartureTimeWeekday?.deleteFromRealm()
        departureTimeIcon?.deleteFromRealm()
        chargingErrorWim?.deleteFromRealm()
        maxSocUpperLimit?.deleteFromRealm()
        minSocUpperLimit?.deleteFromRealm()
        chargingPowerEcoLimit?.deleteFromRealm()
        chargeFlapDCStatus?.deleteFromRealm()
        chargeFlapACStatus?.deleteFromRealm()
        chargeCouplerDCLockStatus?.deleteFromRealm()
        chargeCouplerACLockStatus?.deleteFromRealm()
        chargeCouplerDCStatus?.deleteFromRealm()
        chargeCouplerACStatus?.deleteFromRealm()
        evRangeAssistDriveOnTime?.deleteFromRealm()
        evRangeAssistDriveOnSOC?.deleteFromRealm()
        chargingBreakClockTimer?.clockTimers?.toList()?.forEach { it.deleteFromRealm() }
        chargingBreakClockTimer?.clockTimers?.deleteAllFromRealm()
        chargingBreakClockTimer?.deleteFromRealm()
        chargingPowerControl?.deleteFromRealm()
    }
}
